include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - "**.g.dart"
    - "**.yaml"
linter:
  rules:
    public_member_api_docs: false
    leading_newlines_in_multiline_strings: false
    use_build_context_synchronously: false
