name: services
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  controllers:
    path: ../controllers
  encrypt: ^5.0.1
  get_it: ^7.2.0
  ninja: ^3.0.8
  pointycastle: ^3.4.0

dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.0
