name: mock_generator
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cache:
    path: ../cache
  controllers:
    path: ../controllers
  dio: ^4.0.0-beta7
  latlong2: ^0.8.1
  models:
    path: ../models
  repositories:
    path: ../repositories
  services:
    path: ../services

dev_dependencies:
  json_serializable: ^6.1.3
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
