name: controllers
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  communication_handler:
    path: ../communication_handler
  equatable: ^2.0.3
  http: ^0.13.4
  json_serializable: ^6.1.3
  mime: ^1.0.1
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.1.10
  coverage: ^1.1.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.0
